version: '3.4'
services:
 mariadb:
  image: mariadb:10.2
  environment:
   MYSQL_ROOT_PASSWORD: abc123.
   MYSQL_DATABASE: db_alumnos
   MYSQL_USER: manager
   MYSQL_PASSWORD: abc123.
  volumes:
   - ./db_volume:/var/lib/mysql
 tomcat:
  build: ./build
  volumes:
   - ./webapps:/usr/local/tomcat/webapps
  ports:
   - "8080:8080"
  links:
   - mariadb:mariadb
